# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Happy Path Configurator 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      cypress-run:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
          - name: Run basic test
            uses: cypress-io/github-action@v1
            with:
              start: npm start
              wait-on: 'http://localhost:8000'
              config: baseUrl=https://localhost:8000
